FROM node:16.13.1 as module_installer
WORKDIR /usr/index
COPY package*.json jsconfig*.json yarn.lock ./
RUN yarn install --pure-lockfile
COPY . ./

FROM node:16.13.1
WORKDIR /usr/index
COPY --from=module_installer /usr/index ./
ENV NODE_ENV=development
ENV REACT_APP_VERSION=v1.1.2
ENV GENERATE_SOURCEMAP=false
RUN chmod -R 777 /usr/index
USER node
EXPOSE 3000
CMD ["yarn", "start"]