FROM node:18-alpine as module_installer
WORKDIR /usr/index
COPY package*.json tsconfig*.json yarn.lock ./
RUN yarn install --pure-lockfile
COPY . ./

FROM node:18-alpine
WORKDIR /usr/index
ENV TZ=Asia/Seoul
COPY --from=module_installer /usr/index ./
RUN chmod -R 777 /usr/app
USER node
CMD ["yarn", "dev:start"]