module.exports = [
	{
		name: 'my_little_account_book_backend_1',
		script: 'build/index.js',
		wait_ready: true,
		listen_timeout: 10000,
		env_production: {
			NODE_ENV: 'production',
			EXPRESS_PORT: '7501',
			SOCKET_PORT: '7202',
			IS_MASTER_SERVER: 'Y',
			IS_CRON_ACTIVATE: 'Y',
			IS_KAFKA_ADMIN_ACTIVATE: 'Y',
			IS_KAFKA_PRODUCER_ACTIVATE: 'N',
			IS_KAFKA_CONSUMER_ACTIVATE: 'N',
		},
		env_development: {
			NODE_ENV: 'development',
			EXPRESS_PORT: '3044',
			SOCKET_PORT: '3332',
			IS_MASTER_SERVER: 'Y',
			IS_CRON_ACTIVATE: 'Y',
			IS_KAFKA_ADMIN_ACTIVATE: 'Y',
			IS_KAFKA_PRODUCER_ACTIVATE: 'N',
			IS_KAFKA_CONSUMER_ACTIVATE: 'N',
		},
	},
	{
		name: 'my_little_account_book_backend_2',
		script: 'build/index.js',
		wait_ready: true,
		listen_timeout: 10000,
		env_production: {
			NODE_ENV: 'production',
			EXPRESS_PORT: '7502',
			SOCKET_PORT: '7203',
			IS_MASTER_SERVER: 'N',
			IS_CRON_ACTIVATE: 'N',
			IS_KAFKA_ADMIN_ACTIVATE: 'N',
			IS_KAFKA_PRODUCER_ACTIVATE: 'N',
			IS_KAFKA_CONSUMER_ACTIVATE: 'Y',
		},
		env_development: {
			NODE_ENV: 'development',
			EXPRESS_PORT: '3045',
			SOCKET_PORT: '3333',
			IS_MASTER_SERVER: 'N',
			IS_CRON_ACTIVATE: 'N',
			IS_KAFKA_ADMIN_ACTIVATE: 'N',
			IS_KAFKA_PRODUCER_ACTIVATE: 'N',
			IS_KAFKA_CONSUMER_ACTIVATE: 'Y',
		},
	},
	// {
	// 	name: 'my_little_account_book_backend_3',
	// 	script: 'build/index.js',
	// 	wait_ready: true,
	// 	listen_timeout: 10000,
	// 	env_production: {
	// 		NODE_ENV: 'production',
	// 		EXPRESS_PORT: '7503',
	// 		SOCKET_PORT: '7204',
	// 	},
	// 	env_development: {
	// 		NODE_ENV: 'development',
	// 		EXPRESS_PORT: '3046',
	// 		SOCKET_PORT: '3334',
	// 	},
	// },
];
