name: 'dev_mab_project'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3044:3044'
  redis:
    image: 'redis:7.2.3'
