name: 'database'

services:
  redis_master:
    image: redis:7.2.3
    ports:
      - ${REDIS_MASTER_PORT}:6379
    volumes:
      - cache_data:/data
      - ${REDIS_MASTER_CONF_PATH}:/etc/redis/redis.conf
    command: ['redis-server', '/etc/redis/redis.conf']
    networks:
      dock_net:
        ipv4_address: 172.33.0.9
    container_name: redis_master
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a ${REDIS_MASTER_PW} ping | grep PONG']
      timeout: 5s
      retries: 10

  mysql_master:
    image: mysql:8.4.4
    user: root
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_USER=${MYSQL_MASTER_USER}
      - MYSQL_DATABASE=${MYSQL_MASTER_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_MASTER_PW}
    ports:
      - ${MYSQL_MASTER_PORT}:3306
    volumes:
      - master_data:/var/lib/mysql
      - ${MYSQL_MASTER_CONF_PATH}:/etc/mysql/conf.d
    networks:
      dock_net:
        ipv4_address: 172.33.0.10
    container_name: mysql_master
    restart: always
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h localhost -u ${MYSQL_MASTER_USER} -p${MYSQL_MASTER_PW}']
      timeout: 20s
      retries: 10

  mysql_slave1:
    image: mysql:8.4.4
    platform: linux/x86_64
    user: root
    ports:
      - ${MYSQL_SLAVE1_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_USER=${MYSQL_SLAVE1_USER}
      - MYSQL_DATABASE=${MYSQL_SLAVE1_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_SLAVE1_PW}
    volumes:
      - slave_data:/var/lib/mysql
      - ${MYSQL_SLAVE1_CONF_PATH}:/etc/mysql/conf.d
    networks:
      dock_net:
        ipv4_address: 172.33.0.11
    depends_on:
      mysql_master:
        condition: service_healthy
    container_name: mysql_slave_1
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h localhost -u ${MYSQL_SLAVE1_USER} -p${MYSQL_SLAVE1_PW}']
      timeout: 20s
      retries: 10

volumes:
  master_data:
  slave_data:
  cache_data:

networks:
  dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
