name: 'database'

services:
  redis_master:
    image: redis:7.2.3
    ports:
      - {PORT}:6379
    volumes:
      - cache_data:/data
      - {REDIS_CONF_PATH}:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      dock_net:
        ipv4_address: 172.33.0.9
    container_name: redis_master
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli -a {PW} ping | grep PONG"]
      timeout: 5s
      retries: 10

  mysql_master:
    image: mysql:8.0.20
    user: root
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD={PW}
      - MYSQL_USER={USER_NAME}
      - MYSQL_DATABASE={DATABASE_NAME}
      - MYSQL_PASSWORD={PW}
    ports:
      - {MYSQL_MASTER_PORT}:3306
    volumes:
      - master_data:/var/lib/mysql
      - {MYSQL_CONF_PATH}:/etc/mysql/conf.d
    networks:
      dock_net:
        ipv4_address: 172.33.0.10
    container_name: mysql_master
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "{USER_NAME}", "-p{PW}"]
      timeout: 20s
      retries: 10

  mysql_slave1:
    image: mysql:8.0.20
    platform: linux/x86_64
    user: root
    ports:
      - {MYSQL_SLAVE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD={PW}
      - MYSQL_USER={USER_NAME}
      - MYSQL_DATABASE={DATABASE_NAME}
      - MYSQL_PASSWORD={PW}
    volumes:
      - slave_data:/var/lib/mysql
      - {MYSQL_CONF_PATH}:/etc/mysql/conf.d
    networks:
      dock_net:
        ipv4_address: 172.33.0.11
    depends_on:
      mysql_master:
        condition: service_healthy
    container_name: mysql_slave_1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "{USER_NAME}", "-p{PW}"]
      timeout: 20s
      retries: 10

volumes:
  master_data:
  slave_data:
  cache_data:

networks:
  dock_net:
networks:
  dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
