name: Unit test Important Logic

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - '!backend/k6/**'
  pull_request:
    paths:
      - 'backend/**'
      - '!backend/k6/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Run test
        run: yarn coverage

      - name: Upload test result
        uses: actions/upload-artifact@v3 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: |
            backend/mocha-back-result.json
            backend/coverage

  report:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Record unit test result
        uses: dorny/test-reporter@v1
        if: always()
        with:
          artifact: mocha-back-result
          name: Mocha test
          path: '*.json'
          fail-on-error: 'false'
          reporter: mocha-json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Record coverage result
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: false
