name: CI/CD Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '!frontend/**.md'
      - '.github/workflows/frontend.yml'
    branches: [main]

# 환경설정
env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/mlab-frontimg
  VERSION: ${{ github.sha }}
  FRONTEND_LOG_VOLUME: frontend_log
  FRONT_CONTAINER_NAME: mlab_front

jobs:
  # 빌드 Job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # github repository에서 checkout
      - uses: actions/checkout@v3

      # docker setup
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # 캐싱된 내용 가져오기
      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # GitHub 컨테이너 레지스트리에 로그인
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Docker 빌드 및 푸쉬
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          build-args: |
            FRONT_PORT=${{ secrets.FRONT_PORT }}
            REACT_APP_VERSION=${{ secrets.FRONT_VERSION }}
            GENERATE_SOURCEMAP=${{ secrets.FRONT_SOURCEMAP }}
            REACT_APP_BACKEND_API=${{ secrets.FRONT_API }}
            REACT_APP_SOCKET_SERVER=${{ secrets.FRONT_SOCKET }}
            REACT_APP_MANAGE_NOTICE=${{ secrets.FRONT_MANAGE_NOTICE_LOCATION }}
            REACT_APP_IMAGE_GET_SERVER=${{ secrets.FRONT_IMAGE_STORAGE_SERVER }}

  # 배포 Job
  deploy:
    needs: build # build 후에 실행되도록 정의
    name: Deploy
    runs-on: [self-hosted]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 기존 Container 확인
      - name: Docker Check Existed Container
        id: docker-container-check-result
        run: |
          echo "IS_EXISTED=$(docker container ls | grep ${{ env.FRONT_CONTAINER_NAME }})" >> $GITHUB_OUTPUT

      # 기존 Container가 있는 경우 제거
      - name: Docker Remove Existed Container
        if: ${{ contains(steps.docker-container-check-result.outputs.IS_EXISTED, env.FRONT_CONTAINER_NAME) == true }}
        run: |
          docker stop ${{ env.FRONT_CONTAINER_NAME }}
          docker rm ${{ env.FRONT_CONTAINER_NAME }}

      # 기존 Image 확인
      - name: Docker Check Existed Image
        id: docker-image-check-result
        run: |
          echo "IS_EXISTED=$(docker image ls | grep ${{ env.DOCKER_IMAGE }})" >> $GITHUB_OUTPUT

      # 기존 Image가 있는 경우 제거
      - name: Docker Remove Existed Image
        if: ${{ contains(steps.docker-image-check-result.outputs.IS_EXISTED, env.DOCKER_IMAGE) == true }}
        run: |
          docker rmi ${{ env.DOCKER_IMAGE }}:latest

      # Docker 환경변수 셋팅 및 Volume, Port 설정 값으로 Run
      - name: Docker run
        run: |
          docker run -d \
          -v ${{ env.FRONTEND_LOG_VOLUME }}:/usr/index/log \
          -p ${{ secrets.FRONT_PORT }}:${{ secrets.LOCAL_FRONT_PORT }} \
          --name ${{ env.FRONT_CONTAINER_NAME }} \
          --restart always ${{ env.DOCKER_IMAGE }}:latest
